# Generated by Django 3.0.5 on 2020-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip4_address', models.CharField(max_length=15)),
                ('ip6_address', models.CharField(max_length=39)),
                ('mac_address', models.CharField(max_length=17)),
                ('bandw_in', models.IntegerField(default=0)),
                ('bandw_out', models.IntegerField(default=0)),
                ('bandw_total', models.IntegerField(default=0)),
                ('last_seen', models.CharField(max_length=40)),
            ],
        ),
    ]
